# CircleCI v2.1 Config
version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true
  publish:
    type: boolean
    default: false

##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: &workingDirVar /home/circleci/project
    docker:
      - image: node:16.13

jobs:
  setup:
    executor: default-docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-cache-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .
  lint:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package-lock.json" }}
      - run: npm run lint

  build:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package-lock.json" }}
      - run: npm run build
      - save_cache:
          paths:
            - .
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .

  test-unit:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Execute unit tests
          command: npm run test:unit

  publish_immediate:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Detect pubish targets
          command: chmod +x .circleci/publish_immediate.sh && .circleci/publish_immediate.sh

  publish:
    executor: default-docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: cat .npmrc
      - run: ls -la ./modules/logging-svc/dist/
      - run: echo "published!!!"

  trigger-publish-workflows:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Trigger publish workflow
          command: chmod +x .circleci/publish.sh && .circleci/publish.sh

workflows:
  version: 2
  build_lint_and_test:
    when: << pipeline.parameters.trigger >>
    jobs:
      - setup:
          context: org-global
      - lint:
          context: org-global
          requires:
            - setup
      - build:
          context: org-global
          requires:
            - setup
      - test-unit:
          context: org-global
          requires:
            - build
            - lint
      - publish_immediate:
          context: org-global
          requires:
            - test-unit

#      - trigger-publish-workflows:
#          context: org-global
#          requires:
#            - test-unit
  publish:
    when: << pipeline.parameters.publish >>
    jobs:
      - publish:
          context: org-global

