# CircleCI v2.1 Config
version: 2.1

##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: &workingDirVar /home/circleci/project
    docker:
      - image: node:16.13

jobs:
  setup:
    executor: default-docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-cache-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .
  build:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package-lock.json" }}
      - run: npm run build
      - save_cache:
          paths:
            - modules
          key: build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .
  test-unit:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package-lock.json" }}
            - build-cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Execute unit tests
          command: npm run test:unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test-unit:
          requires:
            - build

