# CircleCI v2.1 Config
version: 2.1

##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: &workingDirVar /home/circleci/project
    docker:
      - image: node:16.13

jobs:
  setup_and_build:
    executor: default-docker
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - save_cache:
          paths:
            - .
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: *workingDirVar
          paths:
            - .
  test-unit:
    executor: default-docker
    steps:
      - attach_workspace:
          at: *workingDirVar
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Execute unit tests
          command: yarn test:unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_and_build
      - test-unit:
          requires:
            - setup_and_build

