#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Ensure we're using the correct Node.js version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
nvm use

# Rebuild native modules if needed
npm rebuild

npm run dep:check
npm run build
npm run lint
npm run test:unit
